// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHKRYYmPSfMKYjNG_UgTP2ZieI_KpmTA8',
    appId: '1:623097037519:web:ad98abd54fc3928f816dba',
    messagingSenderId: '623097037519',
    projectId: 'final-project-2021-0160',
    authDomain: 'final-project-2021-0160.firebaseapp.com',
    storageBucket: 'final-project-2021-0160.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDspQQ73ebq8k0yhrRXvaKA-2XvCRyrdY4',
    appId: '1:623097037519:android:9c674599e5cbe3a7816dba',
    messagingSenderId: '623097037519',
    projectId: 'final-project-2021-0160',
    storageBucket: 'final-project-2021-0160.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgiL5HN1HFK-dQGbrRfsQRhF-nKqOe73g',
    appId: '1:623097037519:ios:0e622d24fa85212b816dba',
    messagingSenderId: '623097037519',
    projectId: 'final-project-2021-0160',
    storageBucket: 'final-project-2021-0160.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgiL5HN1HFK-dQGbrRfsQRhF-nKqOe73g',
    appId: '1:623097037519:ios:0e622d24fa85212b816dba',
    messagingSenderId: '623097037519',
    projectId: 'final-project-2021-0160',
    storageBucket: 'final-project-2021-0160.firebasestorage.app',
    iosBundleId: 'com.example.crudFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHKRYYmPSfMKYjNG_UgTP2ZieI_KpmTA8',
    appId: '1:623097037519:web:fbf0cbc1db8fe7fc816dba',
    messagingSenderId: '623097037519',
    projectId: 'final-project-2021-0160',
    authDomain: 'final-project-2021-0160.firebaseapp.com',
    storageBucket: 'final-project-2021-0160.firebasestorage.app',
  );
}
